BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "booking" (
	"id"	INTEGER NOT NULL,
	"car_id"	INTEGER NOT NULL,
	"borrower_id"	INTEGER,
	"time"	TEXT NOT NULL,
	"date"	TEXT NOT NULL,
	"available"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("car_id") REFERENCES "car"("id")
);
CREATE TABLE IF NOT EXISTS "borrower" (
	"id"	INTEGER NOT NULL,
	"name"	TEXT NOT NULL COLLATE UTF16,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "car" (
	"id"	INTEGER NOT NULL,
	"lender_id"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("lender_id") REFERENCES "lender"("id")
);
CREATE TABLE IF NOT EXISTS "lender" (
	"id"	INTEGER NOT NULL,
	"name"	TEXT NOT NULL COLLATE UTF16,
	PRIMARY KEY("id" AUTOINCREMENT)
);
INSERT INTO "booking" VALUES (1,1,NULL,'06:00','2021-08-11',1);
INSERT INTO "booking" VALUES (2,1,1,'07:00','2021-08-11',0);
INSERT INTO "booking" VALUES (3,3,NULL,'11:00','2021-08-31',1);
INSERT INTO "borrower" VALUES (1,'Borrower one');
INSERT INTO "borrower" VALUES (2,'Borrower two');
INSERT INTO "car" VALUES (1,1);
INSERT INTO "car" VALUES (2,1);
INSERT INTO "car" VALUES (3,2);
INSERT INTO "lender" VALUES (1,'The lender 1');
INSERT INTO "lender" VALUES (2,'The lender 2');
COMMIT;
